<?php
/**
 * @file
 * Display Suite Instruments configuration.
 */

function ds_instruments() {
  return array(
    'label' => t('Instruments'),
    'regions' => array(
      'region_1_1_1' => t('Region 1 (row 1, column 1)'),
      'region_1_1_2' => t('Region 1 (row 1, column 2)'),
      'region_1_2_1' => t('Region 1 (row 2, column 1)'),
      'region_1_3_1' => t('Region 1 (row 3, column 1)'),
      'region_1_3_2' => t('Region 1 (row 3, column 2)'),
      'region_1_3_3' => t('Region 1 (row 3, column 3)'),
      'region_1_4_1' => t('Region 1 (row 4, column 1)'),
      'region_1_4_2' => t('Region 1 (row 4, column 2)')
    ),
    'image' => TRUE
  );
}
