<?php
/**
 * @file
 * Display Suite Meetings configuration.
 */

function ds_meetings() {
  return array(
    'label' => t('Meetings'),
    'regions' => array(
      'region_1_1_1' => t('Region 1 (row 1, column 1)'),
      'region_1_1_2' => t('Region 1 (row 1, column 2)'),
      'region_2' => t('Region 2'),
      'region_3_1_1' => t('Region 3 (row 1, column 1)'),
      'region_3_1_2' => t('Region 3 (row 1, column 2)'),
      'region_3_1_3' => t('Region 3 (row 1, column 3)'),
      'region_3_1_4' => t('Region 3 (row 1, column 4)'),
      'region_4_1_1' => t('Region 4 (row 1, column 1)'),
      'region_4_1_2' => t('Region 4 (row 1, column 2)'),
      'region_5_1_1' => t('Region 5 (row 1, column 1)'),
      'region_5_1_2' => t('Region 5 (row 1, column 2)'),
      'region_6' => t('Region 6'),
      'related_content_1_1' => t('Related content (row 1, column 1)'),
      'related_content_1_2' => t('Related content (row 1, column 2)')
    ),
    'image' => TRUE
  );
}
