<?php
/**
 * @file
 * Display Suite Projects configuration.
 */

function ds_projects() {
  return array(
    'label' => t('Projects'),
    'regions' => array(
      'region_1_1_1' => t('Region 1 (row 1, column 1)'),
      'region_1_1_2' => t('Region 1 (row 1, column 2)'),
      'region_2' => t('Region 2'),
      'region_3_1_1' => t('Region 3 (row 1, column 1)'),
      'region_3_1_2' => t('Region 3 (row 1, column 2)'),
      'region_4' => t('Region 4'),
      'region_5_1_1' => t('Region 5 (row 1, column 1)'),
      'region_5_1_2' => t('Region 5 (row 1, column 2)'),
      'region_5_1_3' => t('Region 5 (row 1, column 3)'),
      'region_6_1_1' => t('Region 6 (row 1, column 1)'),
      'region_6_1_2' => t('Region 6 (row 1, column 2)'),
      'region_6_1_3' => t('Region 6 (row 1, column 3)'),
      'budget_line_bac' => t('Budget line (BAC)'),
      'activity' => t('Activity'),
      'schedule_of_payments' => t('Schedule of payments'),
      'related_content_1_1' => t('Related content (row 1, column 1)'),
      'related_content_1_2' => t('Related content (row 1, column 2)'),
    ),
    'image' => TRUE
  );
}
