<?php
/**
 * This template is used to assemble all nodes selected during newsletter
 * creation with Simplenews Content Selection.
 *
 * The following variables are available:
 *    - $toc Table of content, if it exists, as generated by the function
 *    theme_scs_toc() or your own.
 *    - $nodes Array of built selected nodes, ready to be outputed with the
 *    render() function.
 */
?>
<?php if ($toc): ?>
  <tr style="background-color: #d6dfe8;">
    <td colspan="3" style="border-top: 1px solid #003870; padding-right: 25px;">
      <?php echo $toc; ?>
    </td>
  </tr>
<?php endif; ?>
<tr>
  <td colspan="3">
    <?php foreach ($nodes as $node): ?>
      <?php echo render($node); ?>
    <?php endforeach; ?>
  </td>
</tr>
